/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ctour
 *
 *
 */
import java.util.ArrayList;


public class FenetreQuiz extends javax.swing.JFrame {

    private final ArrayList<Question> listeQuestions;
    private int indexQuestionCourante = 0;
    private int score = 0;

    public FenetreQuiz() {
        initComponents();

        listeQuestions = new ArrayList<>();

        listeQuestions.add(new Question(
                "Quel fleuve traversait l'Égypte ?",
                "Le Tigre", "Le Nil", "L'Euphrate", "Le Jourdain",
                2
        ));
        listeQuestions.add(new Question(
                "Quel pharaon est connu pour avoir construit la grande pyramide de Gizeh  ?",
                "Ramsès II", "Khéops", "Toutankhamon", "Akhenaton",
                2
        ));
        listeQuestions.add(new Question(
                "À quoi servait le Livre des Morts dans l'Égypte ancienne ?",
                "À apprendre la magie", "À guider les défunts dans l'au-delà",
                "À raconter l'histoire des pharaons", "À enseigner l’écriture",
                2
        ));
        listeQuestions.add(new Question(
                "Comment appelait-on les écritures sacrées de l'Égypte ancienne ?",
                "Les hiéroglyphes", "Le cunéiforme", "Le latin", "L’alphabet phénicien",
                1
        ));
        listeQuestions.add(new Question(
                "Quelle divinité était représentée avec une tête de chacal ?",
                "Horus", "Anubis", "Osiris", "Sobek",
                2
        ));

        java.util.Collections.shuffle(listeQuestions);

        afficherQuestionCourante();
    }

    private void afficherQuestionCourante() {
        Question q = listeQuestions.get(indexQuestionCourante);

        lblQuestion.setText(q.getIntitule());
        btnRep1.setText(q.getP1());
        btnRep2.setText(q.getP2());
        btnRep3.setText(q.getP3());
        btnRep4.setText(q.getP4());

        lblFeedback.setText("");
        lblScore.setText("Score : " + score);

        btnRep1.setEnabled(true);
        btnRep2.setEnabled(true);
        btnRep3.setEnabled(true);
        btnRep4.setEnabled(true);
    }

    private void verifierReponse(int choix) {
        Question q = listeQuestions.get(indexQuestionCourante);

        if (choix == q.getIndexBonneReponse()) {
            lblFeedback.setText("Bonne réponse !");
            score++;
            lblScore.setText("Score : " + score);
        } else {
            lblFeedback.setText("Mauvaise réponse...");
        }

        btnRep1.setEnabled(false);
        btnRep2.setEnabled(false);
        btnRep3.setEnabled(false);
        btnRep4.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQuestion = new javax.swing.JLabel();
        btnRep1 = new javax.swing.JButton();
        btnRep2 = new javax.swing.JButton();
        btnRep3 = new javax.swing.JButton();
        btnRep4 = new javax.swing.JButton();
        lblFeedback = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();
        btnQuestionSuivante = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblQuestion.setText("jLabel1");

        btnRep1.setText("jButton1");
        btnRep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep1ActionPerformed(evt);
            }
        });

        btnRep2.setText("jButton2");
        btnRep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep2ActionPerformed(evt);
            }
        });

        btnRep3.setText("jButton3");
        btnRep3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep3ActionPerformed(evt);
            }
        });

        btnRep4.setText("jButton4");
        btnRep4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep4ActionPerformed(evt);
            }
        });

        lblFeedback.setText("jLabel1");

        lblScore.setText("jLabel1");

        btnQuestionSuivante.setText("Question suivante");
        btnQuestionSuivante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuestionSuivanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQuestion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRep2)
                            .addComponent(btnRep1)
                            .addComponent(btnRep3)
                            .addComponent(btnRep4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblScore, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                                .addComponent(btnQuestionSuivante, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRep1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRep2)
                .addGap(18, 18, 18)
                .addComponent(btnRep3)
                .addGap(18, 18, 18)
                .addComponent(btnRep4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(lblFeedback)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblScore)
                    .addComponent(btnQuestionSuivante))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep1ActionPerformed

        verifierReponse(1);
    

    

    }//GEN-LAST:event_btnRep1ActionPerformed

    private void btnQuestionSuivanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuestionSuivanteActionPerformed

        indexQuestionCourante++;

        if (indexQuestionCourante < listeQuestions.size()) {
            afficherQuestionCourante();
        } else {
            lblFeedback.setText("Quiz terminé ! Score final : " + score + " / " + listeQuestions.size());
            btnQuestionSuivante.setEnabled(false);
        }
    

       
    }//GEN-LAST:event_btnQuestionSuivanteActionPerformed

    private void btnRep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep2ActionPerformed
        verifierReponse(2);
    }//GEN-LAST:event_btnRep2ActionPerformed

    private void btnRep3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep3ActionPerformed
        verifierReponse(3);
    }//GEN-LAST:event_btnRep3ActionPerformed

    private void btnRep4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep4ActionPerformed
        verifierReponse(4);
    }//GEN-LAST:event_btnRep4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new FenetreQuiz().setVisible(true));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuestionSuivante;
    private javax.swing.JButton btnRep1;
    private javax.swing.JButton btnRep2;
    private javax.swing.JButton btnRep3;
    private javax.swing.JButton btnRep4;
    private javax.swing.JLabel lblFeedback;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblScore;
    // End of variables declaration//GEN-END:variables

}
