/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author ctour
 */
public class NewJFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame.class.getName());

    private JButton[][] cells = new JButton[5][5];
    private JPanel boardPanel;
    private Piece[][] board = new Piece[5][5];
    private int selectedRow = -1;
    private int selectedCol = -1;
    private Card[] playerCards = new Card[2];
    private Card selectedCard = null;
    private JPanel cardsPanel;
    private boolean redTurn = true; // rouge commence
    private JLabel turnLabel;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        createBoard();
        initPieces();
        initCards();
        initTurnLabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
    }
// ====== CRÉATION DU PLATEAU 5x5 ======

    private void createBoard() {

        boardPanel = new JPanel(new GridLayout(5, 5, 5, 5));
        boardPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        boardPanel.setBackground(Color.DARK_GRAY);

        for (int row = 0; row < 5; row++) {
            for (int col = 0; col < 5; col++) {

                JButton cell = new JButton();
                cell.setPreferredSize(new Dimension(80, 80));
                cell.setFocusPainted(false);

                if ((row + col) % 2 == 0) {
                    cell.setBackground(new Color(245, 245, 220));
                } else {
                    cell.setBackground(new Color(220, 220, 200));
                }

                final int r = row;
                final int c = col;

                cell.addActionListener(e -> onCellClicked(r, c));

                cells[row][col] = cell;
                boardPanel.add(cell);
            }
        }

        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(boardPanel, BorderLayout.CENTER);
    }

    private void onCellClicked(int row, int col) {
        // 1️⃣ Sélection d’un pion
        if (selectedRow == -1 && selectedCol == -1) {

            if (board[row][col] != null) {

                // Vérifier que c’est le bon joueur
                if (board[row][col].isRed() != redTurn) {
                    return;
                }

                selectedRow = row;
                selectedCol = col;

                resetBoardColors();
                cells[row][col].setBackground(Color.ORANGE);

                // Afficher les coups possibles
                if (selectedCard != null) {
                    showPossibleMoves(row, col);
                }
            }
            return;
        }

        // 2️⃣ Tentative de déplacement
        if (isMoveAllowed(selectedRow, selectedCol, row, col)) {
            movePiece(selectedRow, selectedCol, row, col);
            redTurn = !redTurn; // changer de joueur
            updateTurnLabel();
        }

        resetBoardColors();
        selectedRow = -1;
        selectedCol = -1;
    }

    private void initPieces() {

        board[4][0] = new Piece(Piece.Type.STUDENT, true);
        board[4][1] = new Piece(Piece.Type.STUDENT, true);
        board[4][2] = new Piece(Piece.Type.MASTER, true);
        board[4][3] = new Piece(Piece.Type.STUDENT, true);
        board[4][4] = new Piece(Piece.Type.STUDENT, true);

        for (int col = 0; col < 5; col++) {
            cells[4][col].setText(board[4][col].getType() == Piece.Type.MASTER ? "M" : "E");
            cells[4][col].setForeground(Color.RED);
        }

        // Joueur bleu (haut)
        board[0][0] = new Piece(Piece.Type.STUDENT, false);
        board[0][1] = new Piece(Piece.Type.STUDENT, false);
        board[0][2] = new Piece(Piece.Type.MASTER, false);
        board[0][3] = new Piece(Piece.Type.STUDENT, false);
        board[0][4] = new Piece(Piece.Type.STUDENT, false);

        for (int col = 0; col < 5; col++) {
            cells[0][col].setText(board[0][col].getType() == Piece.Type.MASTER ? "M" : "E");
            cells[0][col].setForeground(Color.BLUE);
        }
    }

    private void movePiece(int fromRow, int fromCol, int toRow, int toCol) {
        // Case cible occupée → on ignore pour l’instant
        if (board[toRow][toCol] != null) {
            System.out.println("Case occupée");
            return;
        }

        // Déplacement logique
        board[toRow][toCol] = board[fromRow][fromCol];
        board[fromRow][fromCol] = null;

        // Déplacement visuel
        cells[toRow][toCol].setText(cells[fromRow][fromCol].getText());
        cells[toRow][toCol].setForeground(cells[fromRow][fromCol].getForeground());

        cells[fromRow][fromCol].setText("");

        // Réinitialiser les couleurs
        resetBoardColors();
    }

    private void resetBoardColors() {
        for (int row = 0; row < 5; row++) {
            for (int col = 0; col < 5; col++) {
                if ((row + col) % 2 == 0) {
                    cells[row][col].setBackground(new Color(245, 245, 220));
                } else {
                    cells[row][col].setBackground(new Color(220, 220, 200));
                }
            }
        }
    }

    private void initCards() {
        // Carte Tigre
        List<Move> tigreMoves = new ArrayList<>();
        tigreMoves.add(new Move(0, -2));
        tigreMoves.add(new Move(0, 1));
        Card tigre = new Card("Tigre", tigreMoves);

        // Carte Grue
        List<Move> grueMoves = new ArrayList<>();
        grueMoves.add(new Move(0, -1));
        grueMoves.add(new Move(-1, 1));
        grueMoves.add(new Move(1, 1));
        Card grue = new Card("Grue", grueMoves);

        playerCards[0] = tigre;
        playerCards[1] = grue;

        createCardsPanel();
    }

    private void createCardsPanel() {
        cardsPanel = new JPanel();
        cardsPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 20, 10));

        for (Card card : playerCards) {
            JButton cardButton = new JButton(card.getName());
            cardButton.setPreferredSize(new Dimension(120, 60));

            cardButton.addActionListener(e -> {
                selectedCard = card;
                System.out.println("Carte sélectionnée : " + card.getName());
            });

            cardsPanel.add(cardButton);
        }

        getContentPane().add(cardsPanel, BorderLayout.SOUTH);
        pack();
    }

    private void showPossibleMoves(int row, int col) {
        int direction = board[row][col].isRed() ? -1 : 1;

        for (Move move : selectedCard.getMoves()) {

            int newRow = row + move.dy * direction;
            int newCol = col + move.dx;

            if (newRow < 0 || newRow >= 5 || newCol < 0 || newCol >= 5) {
                continue;
            }

            // Case vide ou capture possible
            if (board[newRow][newCol] == null
                    || board[newRow][newCol].isRed() != board[row][col].isRed()) {

                cells[newRow][newCol].setBackground(Color.GREEN);
            }
        }
    }

    private boolean isMoveAllowed(int fromRow, int fromCol, int toRow, int toCol) {
        if (selectedCard == null) {
            return false;
        }

        int direction = board[fromRow][fromCol].isRed() ? -1 : 1;

        for (Move move : selectedCard.getMoves()) {

            int targetRow = fromRow + move.dy * direction;
            int targetCol = fromCol + move.dx;

            if (targetRow == toRow && targetCol == toCol) {

                // Case vide ou capture ennemie
                return board[toRow][toCol] == null
                        || board[toRow][toCol].isRed() != board[fromRow][fromCol].isRed();
            }
        }
        return false;
    }

    private void initTurnLabel() {
        turnLabel = new JLabel("Tour : Rouge", SwingConstants.CENTER);
        turnLabel.setFont(new Font("Arial", Font.BOLD, 16));
        turnLabel.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));

        getContentPane().add(turnLabel, BorderLayout.NORTH);
    }

    private void updateTurnLabel() {
        turnLabel.setText(redTurn ? "Tour : Rouge" : "Tour : Bleu");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
