/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 *
 * @author ctour
 */
public class NewJFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame.class.getName());

    private JButton[][] cells = new JButton[5][5];
    private JPanel boardPanel;
    private Piece[][] board = new Piece[5][5];
    private int selectedRow = -1;
    private int selectedCol = -1;
    private Card[] playerCards = new Card[2];
    private Card selectedCard = null;
    private JPanel cardsPanel;
    private boolean redTurn = true; // rouge commence
    private JLabel turnLabel;
    private Card middleCard;
    private JButton middleCardButton;
    private JButton[] cardButtons = new JButton[2];
    private static final int RED_TEMPLE_ROW = 4;
    private static final int RED_TEMPLE_COL = 2;

    private static final int BLUE_TEMPLE_ROW = 0;
    private static final int BLUE_TEMPLE_COL = 2;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        createBoard();
        initPieces();

        initCards();         // crée les objets Card + middleCard
        createCardsPanel();  // crée l'UI des cartes une seule fois

        initTurnLabel();

        pack();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
    }
// ====== CRÉATION DU PLATEAU 5x5 ======

    private void createBoard() {

        boardPanel = new JPanel(new GridLayout(5, 5, 5, 5));
        boardPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        boardPanel.setBackground(Color.DARK_GRAY);

        for (int row = 0; row < 5; row++) {
            for (int col = 0; col < 5; col++) {

                JButton cell = new JButton();
                cell.setPreferredSize(new Dimension(80, 80));
                cell.setFocusPainted(false);

                if ((row + col) % 2 == 0) {
                    cell.setBackground(new Color(245, 245, 220));
                } else {
                    cell.setBackground(new Color(220, 220, 200));
                }

                final int r = row;
                final int c = col;

                cell.addActionListener(e -> onCellClicked(r, c));

                cells[row][col] = cell;
                boardPanel.add(cell);
            }
        }

        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(boardPanel, BorderLayout.CENTER);
    }

    private void onCellClicked(int row, int col) {
        // 1️⃣ Sélection d’un pion
        if (selectedRow == -1 && selectedCol == -1) {

            if (board[row][col] != null) {

                // Vérifier que c’est le bon joueur
                if (board[row][col].isRed() != redTurn) {
                    return;
                }

                selectedRow = row;
                selectedCol = col;

                resetBoardColors();
                cells[row][col].setBackground(Color.ORANGE);

                // Afficher les coups possibles
                if (selectedCard != null) {
                    showPossibleMoves(row, col);
                }
            }
            return;
        }

        // 2️⃣ Tentative de déplacement
        if (isMoveAllowed(selectedRow, selectedCol, row, col)) {
            movePiece(selectedRow, selectedCol, row, col);
            exchangeCards();
            redTurn = !redTurn;
            updateTurnLabel();
            if (!redTurn) {
                playAITurn();
            }
        }

        resetBoardColors();
        selectedRow = -1;
        selectedCol = -1;
    }

    private void initPieces() {

        board[4][0] = new Piece(Piece.Type.STUDENT, true);
        board[4][1] = new Piece(Piece.Type.STUDENT, true);
        board[4][2] = new Piece(Piece.Type.MASTER, true);
        board[4][3] = new Piece(Piece.Type.STUDENT, true);
        board[4][4] = new Piece(Piece.Type.STUDENT, true);

        for (int col = 0; col < 5; col++) {
            cells[4][col].setText(board[4][col].getType() == Piece.Type.MASTER ? "M" : "E");
            cells[4][col].setForeground(Color.RED);
        }

        // Joueur bleu (haut)
        board[0][0] = new Piece(Piece.Type.STUDENT, false);
        board[0][1] = new Piece(Piece.Type.STUDENT, false);
        board[0][2] = new Piece(Piece.Type.MASTER, false);
        board[0][3] = new Piece(Piece.Type.STUDENT, false);
        board[0][4] = new Piece(Piece.Type.STUDENT, false);

        for (int col = 0; col < 5; col++) {
            cells[0][col].setText(board[0][col].getType() == Piece.Type.MASTER ? "M" : "E");
            cells[0][col].setForeground(Color.BLUE);
        }
    }

    private void movePiece(int fromRow, int fromCol, int toRow, int toCol) {
        // Interdire de prendre une pièce alliée
        if (board[toRow][toCol] != null
                && board[toRow][toCol].isRed() == board[fromRow][fromCol].isRed()) {
            System.out.println("Case occupée par un allié");
            return;
        }

        // Déplacement logique (capture si une pièce ennemie était là)
        board[toRow][toCol] = board[fromRow][fromCol];
        board[fromRow][fromCol] = null;

        // Déplacement visuel
        cells[toRow][toCol].setText(cells[fromRow][fromCol].getText());
        cells[toRow][toCol].setForeground(cells[fromRow][fromCol].getForeground());
        cells[fromRow][fromCol].setText("");

        resetBoardColors();

        // Vérifier victoire après le coup
        checkVictoryAfterMove(toRow, toCol);

    }

    private void resetBoardColors() {
        for (int row = 0; row < 5; row++) {
            for (int col = 0; col < 5; col++) {
                if ((row + col) % 2 == 0) {
                    cells[row][col].setBackground(new Color(245, 245, 220));
                } else {
                    cells[row][col].setBackground(new Color(220, 220, 200));
                }
            }
        }
    }

    private void initCards() {
        List<Card> allCards = new ArrayList<>();

        // TIGRE
        allCards.add(new Card("Tigre", moves(
                new Move(0, -2),
                new Move(0, 1)
        )));

        // DRAGON
        allCards.add(new Card("Dragon", moves(
                new Move(-2, -1),
                new Move(2, -1),
                new Move(-1, 1),
                new Move(1, 1)
        )));

        // GRENOUILLE
        allCards.add(new Card("Grenouille", moves(
                new Move(-2, 0),
                new Move(-1, -1),
                new Move(1, 1)
        )));

        // LAPIN
        allCards.add(new Card("Lapin", moves(
                new Move(2, 0),
                new Move(1, -1),
                new Move(-1, 1)
        )));

        // CRABE
        allCards.add(new Card("Crabe", moves(
                new Move(-2, 0),
                new Move(0, -1),
                new Move(2, 0)
        )));

        // ÉLÉPHANT
        allCards.add(new Card("Éléphant", moves(
                new Move(-1, 0),
                new Move(-1, -1),
                new Move(1, 0),
                new Move(1, -1)
        )));

        // OIE
        allCards.add(new Card("Oie", moves(
                new Move(-1, 0),
                new Move(-1, -1),
                new Move(1, 0),
                new Move(1, 1)
        )));

        // COQ
        allCards.add(new Card("Coq", moves(
                new Move(-1, 0),
                new Move(-1, 1),
                new Move(1, 0),
                new Move(1, -1)
        )));

        // SINGE
        allCards.add(new Card("Singe", moves(
                new Move(-1, -1),
                new Move(1, -1),
                new Move(-1, 1),
                new Move(1, 1)
        )));

        // MANTE
        allCards.add(new Card("Mante", moves(
                new Move(-1, -1),
                new Move(0, 1),
                new Move(1, -1)
        )));

        // CHEVAL
        allCards.add(new Card("Cheval", moves(
                new Move(0, -1),
                new Move(-1, 0),
                new Move(0, 1)
        )));

        // BŒUF
        allCards.add(new Card("Bœuf", moves(
                new Move(0, -1),
                new Move(1, 0),
                new Move(0, 1)
        )));

        // GRUE
        allCards.add(new Card("Grue", moves(
                new Move(0, -1),
                new Move(-1, 1),
                new Move(1, 1)
        )));

        // SANGLIER
        allCards.add(new Card("Sanglier", moves(
                new Move(-1, 0),
                new Move(0, -1),
                new Move(1, 0)
        )));

        // ANGUILLE
        allCards.add(new Card("Anguille", moves(
                new Move(-1, -1),
                new Move(1, 0),
                new Move(-1, 1)
        )));

        // COBRA
        allCards.add(new Card("Cobra", moves(
                new Move(1, -1),
                new Move(-1, 0),
                new Move(1, 1)
        )));

        // 🎲 Tirage aléatoire
        Collections.shuffle(allCards);

        // Distribution
        playerCards[0] = allCards.get(0);
        playerCards[1] = allCards.get(1);

        // (on fera les cartes du joueur Bleu plus tard si tu veux être ultra fidèle)
        middleCard = allCards.get(4);
    }

    private void createCardsPanel() {
        cardsPanel = new JPanel(new BorderLayout());

        JPanel playerPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 20, 10));

        for (int i = 0; i < 2; i++) {
            JButton btn = new JButton();
            btn.setPreferredSize(new Dimension(120, 60));

            final int index = i;
            btn.addActionListener(e -> {
                selectedCard = playerCards[index];
                if (selectedCard != null) {
                    System.out.println("Carte sélectionnée : " + selectedCard.getName());
                }
            });

            cardButtons[i] = btn;
            playerPanel.add(btn);
        }

        middleCardButton = new JButton();
        middleCardButton.setEnabled(false);
        middleCardButton.setPreferredSize(new Dimension(120, 60));

        cardsPanel.add(playerPanel, BorderLayout.SOUTH);
        cardsPanel.add(middleCardButton, BorderLayout.CENTER);

        getContentPane().add(cardsPanel, BorderLayout.SOUTH);

        updateCardsDisplay(); // ← clé

    }

    private void showPossibleMoves(int row, int col) {
        int direction = board[row][col].isRed() ? 1 : -1;

        for (Move move : selectedCard.getMoves()) {

            int newRow = row + move.dy * direction;
            int newCol = col + move.dx;

            if (newRow < 0 || newRow >= 5 || newCol < 0 || newCol >= 5) {
                continue;
            }

            // Case vide ou capture possible
            if (board[newRow][newCol] == null
                    || board[newRow][newCol].isRed() != board[row][col].isRed()) {

                cells[newRow][newCol].setBackground(Color.GREEN);
            }
        }
    }

    private boolean isMoveAllowed(int fromRow, int fromCol, int toRow, int toCol) {
        if (selectedCard == null) {
            return false;
        }

        int direction = board[fromRow][fromCol].isRed() ? 1 : -1;

        for (Move move : selectedCard.getMoves()) {

            int targetRow = fromRow + move.dy * direction;
            int targetCol = fromCol + move.dx;

            if (targetRow == toRow && targetCol == toCol) {

                // Case vide ou capture ennemie
                return board[toRow][toCol] == null
                        || board[toRow][toCol].isRed() != board[fromRow][fromCol].isRed();
            }
        }
        return false;
    }

    private void initTurnLabel() {
        turnLabel = new JLabel("Tour : Rouge", SwingConstants.CENTER);
        turnLabel.setFont(new Font("Arial", Font.BOLD, 16));
        turnLabel.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));

        getContentPane().add(turnLabel, BorderLayout.NORTH);
    }

    private void updateTurnLabel() {
        turnLabel.setText(redTurn ? "Tour : Rouge" : "Tour : Bleu");
    }

    private void exchangeCards() {
        for (int i = 0; i < 2; i++) {
            if (playerCards[i] == selectedCard) {

                Card temp = middleCard;
                middleCard = playerCards[i];
                playerCards[i] = temp;
                break;
            }
        }

        selectedCard = null;
        updateCardsDisplay();

    }

    private void updateCardsDisplay() {
        for (int i = 0; i < 2; i++) {
            if (playerCards[i] != null) {
                cardButtons[i].setText(playerCards[i].getName());
                cardButtons[i].setEnabled(true);
            } else {
                cardButtons[i].setText("");
                cardButtons[i].setEnabled(false);
            }
        }

        if (middleCard != null) {
            middleCardButton.setText(middleCard.getName());
        }
    }

    private void checkVictoryAfterMove(int row, int col) {

        Piece piece = board[row][col];
        if (piece == null) {
            return;
        }

        // 1️⃣ Victoire par temple
        if (piece.getType() == Piece.Type.MASTER) {

            if (piece.isRed()
                    && row == BLUE_TEMPLE_ROW
                    && col == BLUE_TEMPLE_COL) {
                showWinner("Rouge");
                return;
            }

            if (!piece.isRed()
                    && row == RED_TEMPLE_ROW
                    && col == RED_TEMPLE_COL) {
                showWinner("Bleu");
                return;
            }
        }

        // 2️⃣ Victoire par capture du maître
        boolean redMasterAlive = false;
        boolean blueMasterAlive = false;

        for (int r = 0; r < 5; r++) {
            for (int c = 0; c < 5; c++) {
                Piece p = board[r][c];
                if (p != null && p.getType() == Piece.Type.MASTER) {
                    if (p.isRed()) {
                        redMasterAlive = true;
                    } else {
                        blueMasterAlive = true;
                    }
                }
            }
        }

        if (!redMasterAlive) {
            showWinner("Bleu");
        }
        if (!blueMasterAlive) {
            showWinner("Rouge");
        }
    }

    private void showWinner(String winner) {
        JOptionPane.showMessageDialog(this,
                "Victoire du joueur " + winner + " !",
                "Fin de partie",
                JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);
    }

    private List<Move> moves(Move... moves) {
        List<Move> list = new ArrayList<>();
        for (Move m : moves) {
            list.add(m);
        }
        return list;
    }

    private void playAITurn() {
        List<MoveAction> possibleActions = new ArrayList<>();

        // 1️⃣ Trouver tous les coups possibles
        for (int r = 0; r < 5; r++) {
            for (int c = 0; c < 5; c++) {

                if (board[r][c] != null && !board[r][c].isRed()) {

                    for (Card card : playerCards) {
                        if (card == null) {
                            continue;
                        }

                        int direction = -1; // bleu

                        for (Move move : card.getMoves()) {

                            int newRow = r + move.dy * direction;
                            int newCol = c + move.dx;

                            if (newRow < 0 || newRow >= 5 || newCol < 0 || newCol >= 5) {
                                continue;
                            }

                            if (board[newRow][newCol] == null
                                    || board[newRow][newCol].isRed()) {

                                possibleActions.add(
                                        new MoveAction(r, c, newRow, newCol, card)
                                );
                            }
                        }
                    }
                }
            }
        }

        // 2️⃣ Aucun coup possible (très rare)
        if (possibleActions.isEmpty()) {
            redTurn = true;
            updateTurnLabel();
            return;
        }

        // 3️⃣ Choix aléatoire
        MoveAction action = possibleActions.get(
                (int) (Math.random() * possibleActions.size())
        );

        // 4️⃣ Jouer le coup
        selectedCard = action.card;
        movePiece(action.fromRow, action.fromCol, action.toRow, action.toCol);
        exchangeCards();

        // 5️⃣ Rendre la main au joueur
        redTurn = true;
        updateTurnLabel();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
